export const BEATS = [
  {
    id: 'boot',
    title: 'Boot',
    year: '',
    progressRange: [0, 0.02],
    scrollLocked: true,
    rest: false,
    mobileOnly: false,
    voText: "[exhale into a coughing fit] —oh. Oh shit. Oh shit it's—[cough]—it's starting, it's already going, okay, okay okay okay—do NOT tell them I wasn't ready.",
    camera: { pos: [0, 12, 2], target: [0, 8, -15] },
    orbState: 'blinking',
    buildings: [],
    transitionIn: null,
    scoreCue: 'silence',
    colorGrade: 'void',
  },
  {
    id: 'meta',
    title: 'Meta',
    year: '',
    progressRange: [0.02, 0.05],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "...oh. You're here. You're actually—huh. Hi. Yeah. They hired me for this. Me. To narrate some guy's entire glowing-city-life-situation. The things I do. Anyway.",
    camera: { pos: [8, 8, -12], target: [0, 5, -25] },
    orbState: 'curious',
    buildings: [],
    transitionIn: 'flow',
    scoreCue: 'pad',
    colorGrade: 'void',
  },
  {
    id: 'birth',
    title: 'Birth',
    year: '1991',
    progressRange: [0.05, 0.11],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "Anirudh Venkatesan. Born 1991. Gujarat. Now here's the thing—he's Tamil. A Tamil kid. Born in Gujarat. Which is—[laughs]—that's like ordering a pizza and it shows up at the neighbor's and just decides to live there. Universe made a typo, never hit backspace. Love it. Moving on.",
    camera: { pos: [-10, 5, -2], target: [-4, 3, -8] },
    orbState: 'gentle',
    buildings: ['Hospital_Building_n3d'],
    transitionIn: 'bloom',
    scoreCue: 'piano',
    colorGrade: 'cream',
  },
  {
    id: 'graduation',
    title: 'First Paid Work',
    year: '2009–11',
    progressRange: [0.11, 0.15],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "Business school, IT degree, blah blah, skip it—except—nineteen, twenty years old, people start paying him. Photos. Design.",
    camera: { pos: [11, 9, 0], target: [5, 6, -5] },
    orbState: 'bright',
    buildings: ['BBA-ITM'],
    transitionIn: 'flow',
    scoreCue: 'rhythmic',
    colorGrade: 'acid_yellow',
  },
  {
    id: 'photon',
    title: 'The Photon',
    year: '2011–13',
    progressRange: [0.15, 0.19],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "And listen—[leans in]—here's the part that gets me—light. He starts chasing light. Photons, man. You can't catch a photon. It's the one thing in the whole universe that doesn't experience time—doesn't age, doesn't stop, just goes, forever—and this lunatic looked at the one uncatchable thing in existence and went yeah, that, I'll do that for a living. [laughs] Idiot. Beautiful idiot.",
    camera: { pos: [6, 7, 5], target: [0, 4, 0] },
    orbState: 'bright',
    buildings: [],
    transitionIn: 'flow',
    scoreCue: 'cinematic',
    colorGrade: 'cream',
  },
  {
    id: 'aiesec',
    title: 'AIESEC',
    year: '2012–13',
    progressRange: [0.19, 0.23],
    scrollLocked: false,
    rest: false,
    mobileOnly: false,
    voText: "AIESEC. International exchange. Somewhere in there the world got bigger. He saw what was out there and decided he wanted a piece of it.",
    camera: { pos: [-5, 6, 8], target: [0, 4, 0] },
    orbState: 'curious',
    buildings: ['AIESEC'],
    transitionIn: 'flow',
    scoreCue: 'pad',
    colorGrade: 'cream',
  },
  {
    id: 'veer',
    title: 'The Veer',
    year: '2013–14',
    progressRange: [0.23, 0.27],
    scrollLocked: false,
    rest: false,
    mobileOnly: false,
    voText: "See that building bailing? He bet a whole goddamn year on the country's fanciest art school. Studied his ass off. Didn't. Get. In.",
    camera: { pos: [14, 6, -5], target: [8, 4, -10] },
    orbState: 'dim',
    buildings: ['Schoogle'],
    veerPath: [{ x: 12, z: -10 }, { x: 2, z: 8 }],
    transitionIn: 'veer',
    scoreCue: 'uncertain',
    colorGrade: 'sour_noon',
  },
  {
    id: 'break',
    title: 'The Break',
    year: '2013–14',
    progressRange: [0.27, 0.31],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "…oof. [quiet] Yeah. That one left a crater.",
    camera: { pos: [-3, 5, 2], target: [2, 2, -5] },
    orbState: 'flicker',
    buildings: [],
    transitionIn: 'break',
    scoreCue: 'silence',
    colorGrade: 'graphite',
  },
  {
    id: 'film',
    title: 'Return to Film',
    year: '2015',
    progressRange: [0.31, 0.39],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "So—and this is just statistics, don't look it up—NOT getting into art school meant he was always gonna end up on a movie set, obviously, that's how it works—and he gets good. Good enough a real film hands him a real camera. Half a million people watched it. Nobody gave him that. Earned every frame. [proud] Heh. Look at him go.",
    camera: { pos: [2, 7, 1], target: [-3, 5, -6] },
    orbState: 'bright',
    buildings: ['Movies', 'Corporate Filims', 'Schoogle'],
    explodeBuilding: 'Movies',
    transitionIn: 'veer',
    scoreCue: 'cinematic',
    colorGrade: 'film_warm',
  },
  {
    id: 'film_fall',
    title: 'Film Fall',
    year: '2015–17',
    progressRange: [0.39, 0.43],
    scrollLocked: false,
    rest: false,
    mobileOnly: false,
    voText: "And THEN the movie work just... dries up. Pfft. Gone. Because a career, see, a career is the universe waiting for you to feel cute so it can kick you directly in the dick. It's thermodynamics. Everything you build, the universe wants back. Entropy. We're all just—[cough]—...where was I.",
    camera: { pos: [-4, 5, -5], target: [0, 3, -12] },
    orbState: 'dim',
    buildings: [],
    transitionIn: 'drain',
    scoreCue: 'thinning',
    colorGrade: 'graphite',
  },
  {
    id: 'pixelate',
    title: 'Pixelate Tower',
    year: '2017–21',
    progressRange: [0.43, 0.51],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "Crypto! He pivots to crypto. Yeah. That crypto. And before you—no—shut up—he actually wins the hackathon, actually gets certified, actually lands the grant. Real money. Tech doesn't crawl back, it kicks the door in and pays the rent. [burp] 'scuse me.",
    camera: { pos: [-11, 10, 1], target: [-6, 8, -4] },
    orbState: 'bright',
    buildings: ['Pixelate'],
    explodeBuilding: 'Pixelate',
    transitionIn: 'bloom',
    scoreCue: 'electronic',
    colorGrade: 'red_neon',
  },
  {
    id: 'studio',
    title: 'Haus of Pixels',
    year: '2022',
    progressRange: [0.51, 0.59],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "Builds a studio. Brands businesses all the way across Gujarat. One pixel at a time. One. Pixel. At a time. You know how insane that is? No, you don't, you have a job, probably. Anyway.",
    camera: { pos: [9, 8, -2], target: [2, 6, -6] },
    orbState: 'bright',
    buildings: ['Haus of Pixels', 'Haus work block'],
    explodeBuilding: 'Haus work block',
    transitionIn: 'flow',
    scoreCue: 'full',
    colorGrade: 'full_palette',
  },
  {
    id: 'europe',
    title: 'Animation & Europe',
    year: '2023–24',
    progressRange: [0.59, 0.64],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "Then—simultaneously, like a maniac—he's making a whole animated series AND co-founding a health startup. Tries to drag the entire circus to Europe. Europe goes: 'nah.' [laughs] Europe said nah, man.",
    camera: { pos: [11, 7, -3], target: [4, 5, -8] },
    orbState: 'gentle',
    buildings: ['Buddy Tales', 'KH'],
    veerPath: [{ x: 8, z: -2 }, { x: 0, z: 0 }],
    explodeBuilding: 'Buddy Tales',
    transitionIn: 'veer',
    scoreCue: 'uncertain',
    colorGrade: 'acid_yellow',
  },
  {
    id: 'rabble',
    title: 'Rabble',
    year: '2023–24',
    progressRange: [0.64, 0.68],
    scrollLocked: false,
    rest: false,
    mobileOnly: false,
    voText: "Rabble. A health startup that thought it could punch above its weight. He helped build the engine. Code, coffee, conviction. It nearly worked.",
    camera: { pos: [-7, 6, 10], target: [0, 4, 0] },
    orbState: 'curious',
    buildings: ['Rabble building'],
    transitionIn: 'flow',
    scoreCue: 'pad',
    colorGrade: 'full_palette',
  },
  {
    id: 'pondi',
    title: 'Pondicherry',
    year: '2024→',
    progressRange: [0.68, 0.75],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "So August 2024 he lands in a sleepy little beach town down south and just... stays. Works remote. Chases light from a hammock now. The smug, sun-kissed prick.",
    camera: { pos: [5, 6, -1], target: [-2, 4, -6] },
    orbState: 'gentle',
    buildings: ['Remote Stations-Homes'],
    transitionIn: 'bloom',
    scoreCue: 'acoustic',
    colorGrade: 'tropical_warm',
  },
  {
    id: 'arrival',
    title: 'The Compiled City',
    year: 'today',
    progressRange: [0.75, 0.85],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "And here—okay—here's the thing I actually—[soft]—every win, every faceplant, every dumb gorgeous swing—he compiled it. Into this. A whole city, built out of light. And that's the joke. The cosmic one. We're temporary, man. We rot. But light? Light doesn't. So this one mortal idiot spent his one mortal life chasing the one immortal thing... and left behind a city that glows.",
    camera: { pos: [0, 18, 28], target: [0, 6, 0] },
    orbState: 'bright',
    buildings: [],
    transitionIn: null,
    scoreCue: 'full',
    colorGrade: 'full_glow',
  },
  {
    id: 'cta',
    title: 'Now',
    year: 'today',
    progressRange: [0.85, 0.92],
    scrollLocked: false,
    rest: true,
    mobileOnly: false,
    voText: "[beat] ...that's not nothing. That's—uh—[clears throat]—that's actually kind of everything. And the light's still going. It doesn't stop. Neither does he.",
    camera: { pos: [0, 10, 12], target: [0, 5, 0] },
    orbState: 'bright',
    buildings: [],
    transitionIn: 'flow',
    scoreCue: 'full',
    colorGrade: 'full_glow',
  },
  {
    id: 'handoff',
    title: 'Orb Handoff',
    year: '',
    progressRange: [0.92, 1.0],
    scrollLocked: false,
    rest: false,
    mobileOnly: false,
    voText: "The light'll wait. Light's patient. [inhale] ...unlike me.",
    camera: { pos: [3, 3, 0], target: [0, 2, -5] },
    orbState: 'handoff',
    buildings: [],
    transitionIn: 'flow',
    scoreCue: 'ambient',
    colorGrade: 'full_glow',
  },
];

export const ERA_COLORS = {
  void:         { saturation: 0.6,  contrast: 0.9,  tint: [0.6, 0.58, 0.65] },
  cream:        { saturation: 0.55, contrast: 1.0,  tint: [1.0, 0.92, 0.82] },
  acid_yellow:  { saturation: 0.7,  contrast: 1.1,  tint: [1.0, 0.95, 0.7] },
  sour_noon:    { saturation: 0.5,  contrast: 1.15, tint: [0.95, 0.8, 0.55] },
  graphite:     { saturation: 0.1,  contrast: 0.8,  tint: [0.7, 0.7, 0.72] },
  film_warm:    { saturation: 0.85, contrast: 1.1,  tint: [1.0, 0.92, 0.8] },
  red_neon:     { saturation: 0.9,  contrast: 1.15, tint: [1.0, 0.85, 0.85] },
  full_palette: { saturation: 0.9,  contrast: 1.0,  tint: [1.0, 0.97, 0.9] },
  tropical_warm:{ saturation: 0.8,  contrast: 1.05, tint: [1.0, 0.95, 0.85] },
  full_glow:    { saturation: 1.0,  contrast: 1.0,  tint: [1.0, 1.0, 1.0] },
};
